import {AUTH_RETURN_TYPES, AUTH_SYMBOLS} from "@/di/types/authentication.types";
import {EMAIL_RETURN_TYPES, EMAIL_SYMBOLS} from "@/di/types/email.types";
import {AUTHORIZATION_RETURN_TYPES, AUTHORIZATION_SYMBOLS} from "@/di/types/authorization.types";
import {TODOS_RETURN_TYPES, TODOS_SYMBOLS} from "@/di/types/todos.types";
import {PROFILE_RETURN_TYPES, PROFILE_SYMBOLS} from "@/di/types/profiles.types";
import {SETUP_QUESTIONS_RETURN_TYPES, SETUP_QUESTIONS_SYMBOLS} from "@/di/types/setup-questions.types";
import {CLASSROOM_MODULES_RETURN_TYPES, CLASSROOM_MODULES_SYMBOLS} from "@/di/types/classroom-modules.types";
import {
    CLASSROOM_FINISHED_VIDEOS_RETURN_TYPES,
    CLASSROOM_FINISHED_VIDEOS_SYMBOLS
} from "@/di/types/classroom-finished-videos.types";
import {CLASSROOM_VIDEOS_RETURN_TYPES, CLASSROOM_VIDEOS_SYMBOLS} from "@/di/types/classroom-videos.types";
import {CLASSROOM_SECTIONS_RETURN_TYPES, CLASSROOM_SECTIONS_SYMBOLS} from "@/di/types/classroom-sections.types";
import {JWT_RETURN_TYPES, JWT_SYMBOLS} from "@/di/types/jwt.types";
import {USER_SUBSCRIPTIONS_RETURN_TYPES, USER_SUBSCRIPTIONS_SYMBOLS} from "@/di/types/user-subscriptions.types";
import {USER_BOUGHT_MODULES_RETURN_TYPES, USER_BOUGHT_MODULES_SYMBOLS} from "@/di/types/user-bought-modules.types";
import {MEETINGS_RETURN_TYPES, MEETINGS_SYMBOLS} from "@/di/types/meetings.types";

export const DI_SYMBOLS = {
    ...AUTH_SYMBOLS,
    ...AUTHORIZATION_SYMBOLS,
    ...EMAIL_SYMBOLS,
    ...TODOS_SYMBOLS,
    ...PROFILE_SYMBOLS,
    ...SETUP_QUESTIONS_SYMBOLS,
    ...CLASSROOM_MODULES_SYMBOLS,
    ...CLASSROOM_SECTIONS_SYMBOLS,
    ...CLASSROOM_VIDEOS_SYMBOLS,
    ...CLASSROOM_FINISHED_VIDEOS_SYMBOLS,
    ...JWT_SYMBOLS,
    ...USER_SUBSCRIPTIONS_SYMBOLS,
    ...USER_BOUGHT_MODULES_SYMBOLS,
    ...MEETINGS_SYMBOLS
};

export interface DI_RETURN_TYPES extends
    AUTH_RETURN_TYPES,
    AUTHORIZATION_RETURN_TYPES,
    EMAIL_RETURN_TYPES,
    TODOS_RETURN_TYPES,
    PROFILE_RETURN_TYPES,
    SETUP_QUESTIONS_RETURN_TYPES,
    CLASSROOM_MODULES_RETURN_TYPES,
    CLASSROOM_SECTIONS_RETURN_TYPES,
    CLASSROOM_VIDEOS_RETURN_TYPES,
    CLASSROOM_FINISHED_VIDEOS_RETURN_TYPES,
    JWT_RETURN_TYPES,
    USER_SUBSCRIPTIONS_RETURN_TYPES,
    USER_BOUGHT_MODULES_RETURN_TYPES,
    MEETINGS_RETURN_TYPES
{}