import {AUTH_RETURN_TYPES, AUTH_SYMBOLS} from "@/di/types/authentication.types";
import {EMAIL_RETURN_TYPES, EMAIL_SYMBOLS} from "@/di/types/email.types";
import {AUTHORIZATION_RETURN_TYPES, AUTHORIZATION_SYMBOLS} from "@/di/types/authorization.types";
import {PROFILE_RETURN_TYPES, PROFILE_SYMBOLS} from "@/di/types/profiles.types";
import {SETUP_QUESTIONS_RETURN_TYPES, SETUP_QUESTIONS_SYMBOLS} from "@/di/types/setup-questions.types";
import {CLASSROOM_MODULES_RETURN_TYPES, CLASSROOM_MODULES_SYMBOLS} from "@/di/types/classroom-modules.types";
import {
    CLASSROOM_FINISHED_VIDEOS_RETURN_TYPES,
    CLASSROOM_FINISHED_VIDEOS_SYMBOLS
} from "@/di/types/classroom-finished-videos.types";
import {CLASSROOM_VIDEOS_RETURN_TYPES, CLASSROOM_VIDEOS_SYMBOLS} from "@/di/types/classroom-videos.types";
import {CLASSROOM_SECTIONS_RETURN_TYPES, CLASSROOM_SECTIONS_SYMBOLS} from "@/di/types/classroom-sections.types";
import {JWT_RETURN_TYPES, JWT_SYMBOLS} from "@/di/types/jwt.types";
import {SUBSCRIPTIONS_RETURN_TYPES, SUBSCRIPTIONS_SYMBOLS} from "@/di/types/subscriptions.types";
import {USER_BOUGHT_MODULES_RETURN_TYPES, USER_BOUGHT_MODULES_SYMBOLS} from "@/di/types/user-bought-modules.types";
import {MEETINGS_RETURN_TYPES, MEETINGS_SYMBOLS} from "@/di/types/meetings.types";
import {PAYMENTS_RETURN_TYPES, PAYMENTS_SYMBOLS} from "@/di/types/payments.types";
import {DSK_RETURN_TYPES, DSK_SYMBOLS} from "@/di/types/dsk.types";
import {BANK_ORDERS_RETURN_TYPES, BANK_ORDERS_SYMBOLS} from "@/di/types/bank-orders.types";
import {BACKEND_KEYS_RETURN_TYPES, BACKEND_KEYS_SYMBOLS} from "@/di/types/backend-keys.types";
import {CALENDAR_RETURN_TYPES, CALENDAR_SYMBOLS} from "@/di/types/calendar.types";
import {
    GOOGLE_NOTIFICATION_CHANNELS_SYMBOLS,
    GOOGLE_NOTIFICATION_CHANNELS_RETURN_TYPES
} from "@/di/types/google-notification-types.types";
import {AUTOMATIONS_RETURN_TYPES, AUTOMATIONS_SYMBOLS} from "@/di/types/automations.types";
import {STORAGE_RETURN_TYPES, STORAGE_SYMBOLS} from "@/di/types/storage.types";
import {VIDEO_DESCRIPTIONS_RETURN_TYPES, VIDEO_DESCRIPTIONS_SYMBOLS} from "@/di/types/video-descriptions.types";

const MODULE_DI_SYMBOLS = {};

interface MODULE_RETURN_TYPES {}

export const DI_SYMBOLS = {
    ...MODULE_DI_SYMBOLS,
    ...AUTH_SYMBOLS,
    ...AUTHORIZATION_SYMBOLS,
    ...EMAIL_SYMBOLS,
    ...PROFILE_SYMBOLS,
    ...SETUP_QUESTIONS_SYMBOLS,
    ...CLASSROOM_MODULES_SYMBOLS,
    ...CLASSROOM_SECTIONS_SYMBOLS,
    ...CLASSROOM_VIDEOS_SYMBOLS,
    ...CLASSROOM_FINISHED_VIDEOS_SYMBOLS,
    ...JWT_SYMBOLS,
    ...SUBSCRIPTIONS_SYMBOLS,
    ...USER_BOUGHT_MODULES_SYMBOLS,
    ...MEETINGS_SYMBOLS,
    ...PAYMENTS_SYMBOLS,
    ...DSK_SYMBOLS,
    ...BANK_ORDERS_SYMBOLS,
    ...BACKEND_KEYS_SYMBOLS,
    ...CALENDAR_SYMBOLS,
    ...GOOGLE_NOTIFICATION_CHANNELS_SYMBOLS,
    ...AUTOMATIONS_SYMBOLS,
    ...STORAGE_SYMBOLS,
    ...VIDEO_DESCRIPTIONS_SYMBOLS
};

export interface DI_RETURN_TYPES extends
    MODULE_RETURN_TYPES,
    AUTH_RETURN_TYPES,
    AUTHORIZATION_RETURN_TYPES,
    EMAIL_RETURN_TYPES,
    PROFILE_RETURN_TYPES,
    SETUP_QUESTIONS_RETURN_TYPES,
    CLASSROOM_MODULES_RETURN_TYPES,
    CLASSROOM_SECTIONS_RETURN_TYPES,
    CLASSROOM_VIDEOS_RETURN_TYPES,
    CLASSROOM_FINISHED_VIDEOS_RETURN_TYPES,
    JWT_RETURN_TYPES,
    SUBSCRIPTIONS_RETURN_TYPES,
    USER_BOUGHT_MODULES_RETURN_TYPES,
    MEETINGS_RETURN_TYPES,
    PAYMENTS_RETURN_TYPES,
    DSK_RETURN_TYPES,
    BANK_ORDERS_RETURN_TYPES,
    BACKEND_KEYS_RETURN_TYPES,
    CALENDAR_RETURN_TYPES,
    GOOGLE_NOTIFICATION_CHANNELS_RETURN_TYPES,
    AUTOMATIONS_RETURN_TYPES,
    STORAGE_RETURN_TYPES,
    VIDEO_DESCRIPTIONS_RETURN_TYPES
{}