import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {getLocale, getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import AppStoreProvider from "@/app/_providers/AppStoreProvider";
import AppQueryClientProvider from "@/app/_providers/AppQueryClientProvider";
import ThemeProvider from "@/app/_providers/ThemeProvider";
import ClerkAuthProvider from "@/app/_providers/ClerkAuthProvider";
import { Toaster } from "@/app/_components/ui/shadcn/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
    children: ReactNode
}

export default async function RootLayout({
  children,
}: Readonly<LayoutProps>) {
    const locale = await getLocale()
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning={true}>
        <NextIntlClientProvider messages={messages}>
            <AppStoreProvider>
                <AppQueryClientProvider>
                    <body>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem={true}
                            disableTransitionOnChange={true}
                        >
                            <ClerkAuthProvider locale={locale}>
                                {children}
                                <Toaster
                                    position="top-right"
                                />
                            </ClerkAuthProvider>
                        </ThemeProvider>
                    </body>
                </AppQueryClientProvider>
            </AppStoreProvider>
        </NextIntlClientProvider>
        </html>
    );
}
