apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: profile
  version: default
  rules:
    - name: allow_admins_to_access_all_users
      actions: ["select", "create", "update", "delete"]
      roles:
        - admin
      effect: EFFECT_ALLOW

    - name: allow_mentors_and_moderators_to_read_all_users
      actions: ["select"]
      roles:
        - mentor
        - moderators
      effect: EFFECT_ALLOW

    - name: allow_users_to_access_their_profiles
      actions: [ "select", "update", "delete" ]
      roles:
        - user
      condition:
        match:
          expr: "request.resource.id == request.principal.id"
      effect: EFFECT_ALLOW